server: 
  port: 9003
spring: 
  application:  
    name: tensquare-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.25.129:3306/tensquare_qa?useSSL=false&characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
jwt:
  config:
    key: theliar
    ttl: 3600000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    ip-address: true  #允许服务间跨域
